apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.name" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "app.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  selector:
    matchLabels: {{- include "app.selector" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "app.labels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.topologySpread }}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: {{- include "app.selector" . | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: {{- include "app.selector" . | nindent 14 }}
      {{- end }}
      {{- if .Values.migrations.enabled }}
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.migrations.command | nindent 12 }}
          env: {{- include "app.env" . | nindent 12 }}
          {{- with (include "app.envFrom" .) }}
          envFrom: {{- . | nindent 12 }}
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- end }}
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args: {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
          env: {{- include "app.env" . | nindent 12 }}
          {{- with (include "app.envFrom" .) }}
          envFrom: {{- . | nindent 12 }}
          {{- end }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet: { path: {{ .Values.probes.liveness }}, port: http }
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet: { path: {{ .Values.probes.readiness }}, port: http }
            periodSeconds: 5
            failureThreshold: 2
          {{- end }}
          {{- if .Values.preStopSleepSeconds }}
          lifecycle:
            preStop:
              sleep: { seconds: {{ .Values.preStopSleepSeconds }} }
          {{- end }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
